In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy

In [2]:
def k(H,Ey,Ex,b):
    return Ex@np.transpose(H)@b
Ex=np.array([[1,0.61,0.22],[0.61,1,0.37],[0.22,0.37,1]])
Ey=np.array([[0.5,0],[0,0.5]])
H=np.array([[0,1,0],[0,0,1]])
b=np.linalg.inv(Ey+H@(Ex@np.transpose(H)))
    

In [3]:
K=k(H,Ey,Ex,b)
K

array([[0.39449151, 0.04935876],
       [0.64507122, 0.0875491 ],
       [0.0875491 , 0.64507122]])

In [4]:
y=np.array([[16],[23]])
u=18*np.ones((3,1))
U=u+K@(y-H@u)


In [5]:

U

array([[17.4578108 ],
       [17.14760305],
       [21.05025791]])

In [6]:
cov=(np.identity(3)-K@H)@Ex
cov

array([[0.74850125, 0.19724575, 0.02467938],
       [0.19724575, 0.32253561, 0.04377455],
       [0.02467938, 0.04377455, 0.32253561]])

In [7]:
Ex1=np.identity(3)
K1=k(H,Ey,Ex1,b)

In [8]:
K1

array([[ 0.        ,  0.        ],
       [ 0.70985756, -0.1750982 ],
       [-0.1750982 ,  0.70985756]])

In [9]:
U1=u+K1@(y-H@u)

In [10]:
U1

array([[18.        ],
       [15.7047939 ],
       [21.89948417]])

In [11]:
cov1=(np.identity(3)-K1@H)@Ex1
cov1

array([[1.        , 0.        , 0.        ],
       [0.        , 0.29014244, 0.1750982 ],
       [0.        , 0.1750982 , 0.29014244]])