In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy

In [2]:
def fun(Ex,Ey,H):
    return Ex@np.transpose(H)@np.linalg.inv((Ey+H@Ex@np.transpose(H)))

In [3]:
Ex=np.array([[1,0.61,0.22],[0.61,1,0.37],[0.22,0.37,1]])
Ey=np.array([[0.5,0],[0,0.5]])
H=np.array([[0,1,0],[0,0,1]])

In [14]:
K=fun(Ex,Ey,H)
K

array([[0.39449151, 0.04935876],
       [0.64507122, 0.0875491 ],
       [0.0875491 , 0.64507122]])

In [5]:
u=np.array([[18],[18],[18]])
u

array([[18],
       [18],
       [18]])

In [6]:
U=u+K@(np.array(([[16],[23]]))-H@u)
U
yy=(np.array(([[16],[23]]))-H@u)
yy


array([[-2],
       [ 5]])

In [7]:
U

array([[17.4578108 ],
       [17.14760305],
       [21.05025791]])

In [8]:
cov=(np.identity(3)-K@H)@Ex
cov

array([[0.74850125, 0.19724575, 0.02467938],
       [0.19724575, 0.32253561, 0.04377455],
       [0.02467938, 0.04377455, 0.32253561]])

In [9]:
Ex1=np.identity(3)
Ey1=0.5*np.identity(2)


In [10]:
def fun1(Ex1,Ey1,H):
    return Ex1@np.transpose(H)@np.linalg.inv((Ey1+H@Ex1@np.transpose(H)))

In [11]:
K1=fun1(Ex1,Ey1,H)
K1

array([[0.        , 0.        ],
       [0.66666667, 0.        ],
       [0.        , 0.66666667]])

In [12]:
U1=u+K1@(np.array(([[16],[23]]))-H@u)
U1

array([[18.        ],
       [16.66666667],
       [21.33333333]])

In [13]:
cov1=(np.identity(3)-K1@H)@Ex1
cov1

array([[1.        , 0.        , 0.        ],
       [0.        , 0.33333333, 0.        ],
       [0.        , 0.        , 0.33333333]])